---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: ublue-cherenkov
# description will be included in the image's metadata
description: My personal OS image featuring the Niri Wayland compositor.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/base-main
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: dnf
    install:
      packages:
        # Niri stuff
        - xwayland-satellite
        - xdg-desktop-portal-gnome
        - xdg-desktop-portal-gtk
        # interface stuff
        - fuzzel
        - waybar
        - swaylock
        - swayidle
        - swaybg
        - wlogout
        - cliphist
        # system stuff
        - foot
        - gammastep
        - brightnessctl
        - kanshi
        - wl-mirror
        - gnome-disk-utility
        - fontconfig
        - xfce-polkit
        - polkit
        - gnome-keyring
        - seahorse
        - libsecret
        - power-profiles-daemon
        - fastfetch
        # session manager
        - greetd
        - tuigreet
        # audio stuff
        - pipewire
        - pipewire-alsa 
        - pipewire-pulseaudio
        - pipewire-config-raop
        - pipewire-gstreamer
        - pipewire-jack-audio-connection-kit
        - pipewire-libs
        - pipewire-plugin-libcamera
        - pipewire-utils
        - wireplumber
        - pavucontrol
        # wireless stuff
        - iwd
        - NetworkManager
        - network-manager-applet
        - nm-connection-editor
        - nm-connection-editor-desktop
        - NetworkManager-bluetooth
        - bluez
        - blueman
        # file manager stuff
        - tumbler
        - gvfs-mtp
        - gvfs-nfs
        - gvfs
        - gvfs-client
        - Thunar
        - thunar-volman
        - thunar-archive-plugin
        - file-roller
        # yazi stuff
        - ripgrep
        - 7zip
        - jq
        - fd-find
        - R-rsvg
        - ImageMagick
        - poppler
        - zoxide
        - chafa
        
  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/yalter/niri/repo/fedora-%OS_VERSION%/yalter-niri-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/erikreider/SwayNotificationCenter/repo/fedora-%OS_VERSION%/erikreider-SwayNotificationCenter-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/erikreider/swayosd/repo/fedora-%OS_VERSION%/erikreider-swayosd-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/lihaohong/yazi/repo/fedora-%OS_VERSION%/lihaohong-yazi-fedora-%OS_VERSION%.repo
    install:
      - starship
      - SwayNotificationCenter
      - swayosd
      - yazi
    remove:
      # example: removing firefox (in favor of the flatpak)
      # "firefox" is the main package, "firefox-langpacks" is a dependency
      - firefox
      - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: script
    snippets:
        - dnf --setopt=install_weak_deps=False --best install niri -y

  - type: default-flatpaks
    configurations:
      - notify: false
        scope: system
        repo:
          title: Flathub (system)
        install:
          - app.zen_browser.zen
          - com.github.tchx84.Flatseal
          - io.github.flattool.Warehouse
          - app.devsuite.Ptyxis
          - io.github.kolunmi.Bazaar
          # default-ish apps
          - io.missioncenter.MissionCenter
          - io.mpv.Mpv
          - org.onlyoffice.desktopeditors
          - org.gnome.eog
          - org.gnome.Snapshot
          - be.alexandervanhee.gradia
          - org.gnome.Calculator
          - org.gnome.clocks

  - type: fonts
    fonts:
      nerd-fonts:
        - JetBrainsMono
  
  - type: files
    files:
      # xdg-desktop-portal config
      - source: system/usr/portals.conf
        destination: /usr/share/xdg-desktop-portal/niri-portals.conf
      # greetd tuigreet-specific config
      - source: system/etc/greetd/config.toml
        destination: /etc/greetd
      # NetworkManager enable iwd
      - source: system/etc/wifi_backend.conf
        destination: /etc/NetworkManager/conf.d
      # waybar baseline configs
      - source: system/etc/waybar
        destination: /etc/xdg/waybar
      # niri baseline config
      - source: system/etc/niri/config.kdl
        destination: /etc/niri/config.kdl
      # adjusted fuzzel config
      - source: system/etc/fuzzel/fuzzel.ini
        destination: /etc/xdg/fuzzel/fuzzel.ini
      # adjusted foot config
      - source: system/etc/foot/foot.ini
        destination: /etc/xdg/foot/foot.ini
      # adjusted swaync configs
      - source: system/etc/swaync
        destination: /etc/xdg/swaync
        
  - type: script
    snippets:
        - "systemctl enable greetd"
        - "systemctl enable swayosd-libinput-backend.service"

  - type: signing # this sets up the proper policy & signing files for signed images to work fully