---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: ublue-cherenkov
# description will be included in the image's metadata
description: This is my personal OS image featuring the SwayFX Wayland compositor.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/base-main
image-version: 42 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/swayfx/swayfx/repo/fedora-%OS_VERSION%/swayfx-swayfx-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/erikreider/SwayNotificationCenter/repo/fedora-%OS_VERSION%/erikreider-SwayNotificationCenter-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/lihaohong/yazi/repo/fedora-%OS_VERSION%/lihaohong-yazi-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/tofik/nwg-shell/repo/fedora-%OS_VERSION%/tofik-nwg-shell-fedora-%OS_VERSION%.repo
    install:
      - micro
      - starship
      - swayfx
      - SwayNotificationCenter
      - yazi
      - nwg-displays
    remove:
      # example: removing firefox (in favor of the flatpak)
      # "firefox" is the main package, "firefox-langpacks" is a dependency
      - firefox
      - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: dnf
    install:
      packages:
        # interface stuff
        - fuzzel
        - waybar
        - sddm
        - sddm-wayland-sway
        - foot
        - gammastep
        - brightnessctl
        - swaybg
        - swaylock
        - swayidle
        - kanshi
        - wl-mirror
        - clipman
        - kde-partitionmanager
        - wlogout
        - rofimoji
        - fontconfig
        # audio stuff
        - pipewire
        - wireplumber
        # wireless stuff
        - NetworkManager
        - blueman
        # cli things
        - fastfetch
        - cmatrix # because it looks cool
        # file manager stuff
        - tumbler
        - gvfs-mtp
        - gvfs-nfs
        - gvfs
        - Thunar
        - thunar-volman
        - thunar-archive-plugin
        # for building bzmenu/iwmenu
        #- rust
        #- cargo
        #- dbus
        #- bluez
        #- iwd
        #- pkgconf              
      
  - type: default-flatpaks
    configurations:
      - scope: user
      - notify: true # Send notification after install/uninstall is finished (true/false)
        repo:
          title: Flathub (user)
        install:
          - app.zen_browser.zen
          - com.github.tchx84.Flatseal
          - io.github.flattool.Warehouse
          # default-ish apps
          - io.missioncenter.MissionCenter
          - io.mpv.Mpv
          - org.libreoffice.LibreOffice
          - org.flameshot.Flameshot
          - net.blumia.pineapple-pictures
          - org.kde.kamoso
          - org.kde.kcalc
          - org.gnome.clocks
        remove:
          # - org.gnome.eog

  - type: fonts
    fonts:
      nerd-fonts:
        - JetBrainsMono
        - Iosevka
  
  #- type: script # install bzmenu, iwmenu
   # snippets:
    #  #- "git clone https://github.com/e-tho/bzmenu /tmp/bzmenu"
     # - "mkdir -p ~/.scripts"
      #- "git clone https://github.com/e-tho/iwmenu && cd iwmenu && cargo build --release && cp target/release/iwmenu ~/.scripts && chmod +x ~/.scripts/iwmenu"
      #- "cd .."
      #- "git clone https://github.com/e-tho/bzmenu && cd bzmenu && cargo build --release && cp target/release/bzmenu ~/.scripts && chmod +x ~/.scripts/bzmenu"
      #- "cd .."
      #- "rm -r iwmenu"

  - type: script 
    snippets:
      - "systemctl set-default graphical.target"
      - "systemctl enable sddm.service"

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

