---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: ublue-cherenkov
# description will be included in the image's metadata
description: My personal OS image featuring the Niri Wayland compositor.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/base-main
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: dnf
    install:
      packages:
        # Niri stuff
        - xwayland-satellite
        - xdg-desktop-portal-gnome
        # interface stuff
        - fuzzel
        - waybar
        - greetd
        - tuigreet
        - foot
        - gammastep
        - brightnessctl
        - swaybg
        - swaylock
        - swayidle
        - kanshi
        - wl-mirror
        - cliphist
        - kde-partitionmanager
        - wlogout
        - rofimoji
        - fontconfig
        - polkit-kde
        - gnome-keyring
        - fastfetch
        # audio stuff
        - pipewire
        - pipewire-alsa 
        - pipewire-pulseaudio
        - pipewire-config-raop
        - pipewire-gstreamer
        - pipewire-jack-audio-connection-kit
        - pipewire-libs
        - pipewire-plugin-libcamera
        - pipewire-utils
        - wireplumber
        # wireless stuff
        - NetworkManager
        - network-manager-applet
        - nm-connection-editor
        - nm-connection-editor-desktop
        - NetworkManager-bluetooth
        - bluez
        - blueman
        # file manager stuff
        - tumbler
        - gvfs-mtp
        - gvfs-nfs
        - gvfs
        - gvfs-client
        - Thunar
        - thunar-volman
        - thunar-archive-plugin
        # yazi stuff
        - ripgrep
        - 7zip
        - jq
        - fd-find
        - R-rsvg
        - ImageMagick
        - poppler
        - zoxide
        
  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/yalter/niri/repo/fedora-%OS_VERSION%/yalter-niri-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/erikreider/SwayNotificationCenter/repo/fedora-%OS_VERSION%/erikreider-SwayNotificationCenter-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/lihaohong/yazi/repo/fedora-%OS_VERSION%/lihaohong-yazi-fedora-%OS_VERSION%.repo
    install:
      - starship
      - niri
      - SwayNotificationCenter
      - yazi
    remove:
      # example: removing firefox (in favor of the flatpak)
      # "firefox" is the main package, "firefox-langpacks" is a dependency
      - firefox
      - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: dnf
    remove:
      packages:
        - wofi
        - rofi
        - rofi-themes
        - alacritty

  - type: default-flatpaks
    configurations:
      - notify: false
        scope: system
        repo:
          title: Flathub (system)
        install:
          - app.zen_browser.zen
          - com.github.tchx84.Flatseal
          - io.github.flattool.Warehouse
          - app.devsuite.Ptyxis
          - io.github.kolunmi.Bazaar
          # default-ish apps
          - io.missioncenter.MissionCenter
          - io.mpv.Mpv
          - org.onlyoffice.desktopeditors
          - net.blumia.pineapple-pictures
          - org.gnome.Snapshot
          - be.alexandervanhee.gradia
          - org.gnome.Calculator
          - org.gnome.clocks

  - type: fonts
    fonts:
      nerd-fonts:
        - JetBrainsMono
  
  - type: files
    files: 
      # greetd tuigreet-specific config
      - source: system/etc/greetd/config.toml
        destination: /etc/greetd
        
  - type: script
    snippets:
        - "systemctl enable greetd"

  - type: signing # this sets up the proper policy & signing files for signed images to work fully